workflows:
  react-native-android-apk:
    name: React Native Android APK - SmartBudget
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.smartbudget"
        APP_NAME: "SmartBudget"
      node: 18.19.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > $CM_BUILD_DIR/android/local.properties
      - name: Setup Gradle Wrapper
        script: |
          cd android
          chmod +x gradlew || true
          # Asegurar que el wrapper existe
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper jar not found, will be downloaded during build"
          fi
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com  # Reemplaza con tu email
        notify:
          success: true
          failure: true

